### ISSUE TITLE
Missed the opportunity to call the mod 'AutoAutoStrut'

### ISSUE THREAD

**Issue by minerscale** [Xyphos/KSP_FullAutoStrut#2]
I just think that's a shame.

Close this issue whenever you feel like.

**Comment by Xyphos** [comment]
it's named in a "Wheel of Fortune" "Before & After" Format; Full-Auto & Auto-Strut.
"AutoAutoStrut" is just redundant.
Thanks for your "helpful" contribution.

**Comment by minerscale** [comment]
Will admit, that is awesome. Completely missed that.

Thank you for your helpful answer :)
